spring:
  application:
    name: safeai
  ai:
    mcp:
      client:
        enabled: true
        sse:
          connections:
            ims-server:
              url: http://localhost:8087
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-5.4
      embedding:
        options:
          model: text-embedding-3-small
    vectorstore:
      chroma:
        client:
          host: http://localhost
          port: 8085
        initialize-schema: true
server:
  port: 8083
